n1 = float(input('Escreva um valor em metros: '))

km = (n1/1000)
hm = (n1/100)
dam = (n1/10)
dm = (n1*10)
cm = (n1*100)
mm = (n1*1000)
print(f'O valor de {n1:.1f}m em quilometros é de {km}')
print(f'O valor de {n1:.1f}m em hectometros é de {hm}')
print(f'O valor de {n1:.1f}m em decametros é de {dam}')
print(f'O valor de {n1:.1f}m em decimetros é de {dm}')
print(f'O valor de {n1:.1f}m em centímetros é de {cm}')
print(f'O valor de {n1:.1f}m em milímetros é de {mm}')